name: Publish Docker image

on:
  schedule:
    - cron: '0 1 * * 7' # every Sunday at 1 am
  workflow_dispatch: # on button click

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------
      # BARE Z3
      # -------
      - name: Extract metadata (tags, labels) for Bare Z3 Docker Image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: deemetree/z3-fork
          tags: |
            type=schedule,prefix=bare-z3-ubuntu-20.04-,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch,prefix=bare-z3-ubuntu-20.04-
            type=ref,event=tag,prefix=bare-z3-ubuntu-20.04-
            type=edge,prefix=bare-z3-ubuntu-20.04-

      - name: Build and push Bare Z3 Docker Image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          target: bare-z3
          file: ./docker/ubuntu-20-04.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}