name: Publish Docker image

on:
  schedule:
    - cron: "0 1 * * 0" # every Sunday at 1 am
  workflow_dispatch: # on button click

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------
      # BARE Z3
      # -------
      - name: Extract metadata (tags, labels) for Bare Z3 Docker Image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: deemetree/z3-fork
          tags: |
            type=schedule,prefix=ubuntu-20.04-bare-z3-,pattern={{date 'YYYYMMDD'}}
            type=ref,event=tag,prefix=ubuntu-20.04-bare-z3-
            type=sha,prefix=ubuntu-20.04-bare-z3-
            type=edge,prefix=ubuntu-20.04-bare-z3-

      - name: Build and push Bare Z3 Docker Image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          target: bare-z3
          file: ./docker/ubuntu-20-04.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=deemetree/z3-fork:buildcache
          cache-to: type=registry,ref=deemetree/z3-fork:buildcache,mode=max

      # ------------------------------
      # Repo description on Docker Hub
      # ------------------------------
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          repository: deemetree/z3
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: ${{ github.event.repository.description }}
